[[redirects]]
  from = "http://khyatifoods.in/*"
  to = "https://khyatifoods.in/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
